# Generated by Django 4.1.5 on 2023-01-31 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100)),
                ('arrive_date', models.DateTimeField(help_text='Format: 2022-01-01 12:00')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV')], max_length=10)),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('special_requirements', models.CharField(blank=True, max_length=400)),
                ('is_sharable', models.BooleanField(default=False)),
                ('driver', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sharer', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sharer_seats', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Open', max_length=10)),
                ('totalRequiredSeats', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
