# Generated by Django 4.1.5 on 2023-02-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passenger_num',
            new_name='owner_seats',
        ),
    ]
