# Generated by Django 4.1.5 on 2023-02-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_passenger_num_ride_owner_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arrive_date',
            new_name='arrive_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='addr',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='is_sharable',
            new_name='sharable',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='totalRequiredSeats',
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requirements',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
