# Generated by Django 4.1.5 on 2023-02-02 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 0, 51, 14, 38998, tzinfo=datetime.timezone.utc), help_text='Format: 01/01/2022, 12:00'),
        ),
    ]
