# Generated by Django 4.1.5 on 2023-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(help_text='Format: 01/01/2022, 12:00'),
        ),
    ]
