# Generated by Django 4.1.5 on 2023-02-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Confirmed', max_length=10),
        ),
    ]
