# Generated by Django 4.1.5 on 2023-01-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('car_type', models.SmallIntegerField(choices=[(1, 'Sedan'), (2, 'SUV')], verbose_name='car_type')),
                ('licenseNum', models.CharField(max_length=100, verbose_name='licenseNum')),
                ('plateNum', models.CharField(max_length=100, verbose_name='licenseNum')),
                ('max_pgers', models.IntegerField(verbose_name='max_pgers')),
                ('special_info', models.CharField(max_length=30, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
            ],
        ),
    ]
