# Generated by Django 4.1.5 on 2023-01-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_rider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='RiderInfo',
        ),
    ]
