# Generated by Django 4.1.5 on 2023-01-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_rider_riderinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='DriverInfo',
        ),
    ]
