# Generated by Django 4.1.5 on 2023-01-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_driver_driverinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverInfo',
        ),
        migrations.DeleteModel(
            name='RiderInfo',
        ),
    ]
