# Generated by Django 4.1.5 on 2023-01-30 02:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_delete_driverinfo_delete_riderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('car_type', models.SmallIntegerField(choices=[(1, 'Sedan'), (2, 'SUV')], verbose_name='car_type')),
                ('licenseNum', models.CharField(max_length=100, verbose_name='licenseNum')),
                ('plateNum', models.CharField(max_length=100, verbose_name='licenseNum')),
                ('max_pgers', models.IntegerField(verbose_name='max_pgers')),
                ('special_info', models.CharField(max_length=30, verbose_name='username')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
