# Generated by Django 4.1.5 on 2023-01-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderinfo',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='DriverInfo',
        ),
        migrations.DeleteModel(
            name='RiderInfo',
        ),
    ]
