# Generated by Django 4.1.5 on 2023-01-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderinfo',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
