# Generated by Django 4.1.5 on 2023-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_driverinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='riderinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
    ]
