# Generated by Django 4.1.5 on 2023-02-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_driverinfo_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Van', 'Van')], max_length=10, verbose_name='car_type'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='special_info',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='special_information'),
        ),
    ]
