# Generated by Django 4.1.5 on 2023-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_driverinfo_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='plateNum',
            field=models.CharField(max_length=100, verbose_name='plateNum'),
        ),
    ]
